name: draw_guess
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core dependencies
  auto_route: ^3.2.4
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dartz: ^0.10.1
  device_preview: ^1.0.0
  google_fonts: ^2.3.1
  material_design_icons_flutter: ^5.0.6595
  flash: ^2.0.3+2
  easy_localization: ^3.0.0
  dio: ^4.0.6
  path_provider: ^2.0.9
  intl: ^0.17.0
  permission_handler: ^9.2.0

  # firebase
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  cloud_functions: ^3.2.12
  firebase_database: ^9.0.11
  firebase_storage: ^10.2.12
  firebase_messaging: ^11.2.13

  # authentication
  google_sign_in: ^5.3.0

  # image
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  cached_network_image: ^3.2.0
  image: ^3.1.3

  # unit test
  firebase_auth_mocks: ^0.8.4
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: ^1.2.2
  firebase_storage_mocks: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
