// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_h7z-UK78UBSfS5o7qy0ard8ATjO-E4',
    appId: '1:950759181931:web:c7e8bf9dd5fce57227eb2e',
    messagingSenderId: '950759181931',
    projectId: 'drawguess-c8775',
    authDomain: 'drawguess-c8775.firebaseapp.com',
    databaseURL: 'https://drawguess-c8775-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drawguess-c8775.appspot.com',
    measurementId: 'G-3M2FPV1VDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfriQwaBKmVYa8_ovFs3KzRKPCTLy5HXw',
    appId: '1:950759181931:android:d093e73933c7e7f027eb2e',
    messagingSenderId: '950759181931',
    projectId: 'drawguess-c8775',
    databaseURL: 'https://drawguess-c8775-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drawguess-c8775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNa9610EPgLNy10ahh1ZLs_8SmmAXhvnA',
    appId: '1:950759181931:ios:0e81beb8798353dc27eb2e',
    messagingSenderId: '950759181931',
    projectId: 'drawguess-c8775',
    databaseURL: 'https://drawguess-c8775-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'drawguess-c8775.appspot.com',
    iosClientId: '950759181931-jad788thjp0hitp3d3frbs9mv57klthj.apps.googleusercontent.com',
    iosBundleId: 'com.drawGuess.app',
  );
}
